### ISSUE TITLE
[Question] mcsms应为daemon的地址

### ISSUE THREAD

**Issue by Zhou-Shilin** [unitwk/mc-server-status-center#3]
`mcsms.json`的url(addr)填写的是web的地址，但是需要提供的key却是daemon的。
我的web连接了4台服务器daemon，如何指定使用哪个服务器？
尝试填写其中一个daemon的key，连接显示403。

**Comment by yumao233** [comment]
只能你自己试试了，这个项目我是很早之前写的，现在已经忘记它的逻辑。

**Comment by Zhou-Shilin** [comment]
6 我去翻翻代码
